# Site settings
title: openHAB 2 
description: Empowering the Smart Home
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.openhab.org" # the base hostname & protocol for your site
twitter_username: openhab
github_username:  openhab
# Build settings
markdown: kramdown
exclude: ["CNAME", "pom.xml", "README.md", "CONTRIBUTING.md"]
# Additional gems for sitemap generation
gems:
  - jekyll-sitemap
  - jekyll-redirect-from