# Site settings
title: openHAB 2.0
description: empowering the smart home
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.openhab.org" # the base hostname & protocol for your site
twitter_username: openhab
github_username:  openhab
permalink: /404.html
# Build settings
markdown: kramdown
exclude: ["CNAME", "pom.xml", "README.md", "CONTRIBUTING.md"]
