# Yekyll site settings
title: openHAB 2
description: Empowering the Smart Home
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.openhab.org" # the base hostname & protocol for your site
twitter_username: openhab
github_username:  openhab
# Build settings
markdown: kramdown
exclude: ["CNAME", "pom.xml", "README.md", "CONTRIBUTING.md", "process_addons.groovy", "update.sh", "Vagrantfile"]
# Additional gems for sitemap generation
plugins:
  - jekyll-sitemap
collections:
  addons_actions:
    output: true
    permalink: /addons/:collection/:path:output_ext
  addons_bindings:
    output: true
    permalink: /addons/:collection/:path:output_ext
  addons_iconsets:
    output: true
    permalink: /addons/:collection/:path:output_ext
  addons_io:
    output: true
    permalink: /addons/:collection/:path:output_ext
  addons_persistence:
    output: true
    permalink: /addons/:collection/:path:output_ext
  addons_transformations:
    output: true
    permalink: /addons/:collection/:path:output_ext
  addons_uis:
    output: true
    permalink: /addons/:collection/:path:output_ext
  addons_voices:
    output: true
    permalink: /addons/:collection/:path:output_ext
defaults:
  -
    scope:
      path: ""
      type: addons_actions
    values:
      layout: addon
  -
    scope:
      path: ""
      type: addons_bindings
    values:
      layout: addon
  -
    scope:
      path: ""
      type: addons_iconsets
    values:
      layout: addon
  -
    scope:
      path: ""
      type: addons_io
    values:
      layout: addon
  -
    scope:
      path: ""
      type: addons_persistence
    values:
      layout: addon
  -
    scope:
      path: ""
      type: addons_transformations
    values:
      layout: addon
  -
    scope:
      path: ""
      type: addons_uis
    values:
      layout: addon
  -
    scope:
      path: ""
      type: addons_voices
    values:
      layout: addon
